#include <strings.h>

namespace Strings
{
   AtString id("id");
   AtString receive_shadows("receive_shadows");
   AtString self_shadows("self_shadows");
   AtString invert_normals("invert_normals");
   AtString opaque("opaque");
   AtString use_light_group("use_light_group");
   AtString use_shadow_group("use_shadow_group");
   AtString ray_bias("ray_bias");
   AtString visibility("visibility");
   AtString sidedness("sidedness");
   AtString shader("shader");
   AtString light_group("light_group");
   AtString shadow_group("shadow_group");
   AtString trace_sets("trace_sets");
   AtString motion_start("motion_start");
   AtString motion_end("motion_end");
   AtString matte("matte");
   AtString transform_type("transform_type");
   AtString volume_padding("volume_padding");
   AtString step_size("step_size");
   AtString instance_num("instance_num");
   AtString bounds_slack("bounds_slack");
   AtString name("name");
   AtString matrix("matrix");
   AtString box("box");
   AtString ginstance("ginstance");
   AtString points("points");
   AtString curves("curves");
   AtString polymesh("polymesh");
   AtString basis("basis");
   AtString num_points("num_points");
   AtString mode("mode");
   AtString node("node");
   AtString inherit_xform("inherit_xform");
}
